### ISSUE TITLE
Tree hash not showing?

### ISSUE THREAD

**Issue by miguelmota** [alessioalex/git-parse-commit#2]
The tree hash is not being returned. Here's the example input: 

```
tree 00dd089c310aea2b821d23ea0f1a6a6235ad165c
parent 32f04c7f572bf75a266268c6f4d8c92731dc3b7f
author Miguel Mota <hello@miguelmota.com> 1560727622 -0700
committer Miguel Mota <hello@miguelmota.com> 1560727622 -0700
gpgsig -----BEGIN PGP SIGNATURE-----

 iQIzBAABCAAdFiEEkA8ilwQdtHsQgZEbZ+wRYViKAPkFAl0G0EYACgkQZ+wRYViK
 APmWdxAAgWKOQpz1/QbzYxOXQZ5uT8lTVnxw8HN4KZaZ36ehFTxzRVO0IEniJGr4
 5+sVskMDbkP/aKQyS/UUmeXKGeYQT4Kpwvtih5CZHSLNO2LQ8pz5o0wjWK8OHmx7
 pGuAd83gMqfnQF7+KDqpxqHR63NDmuRo4QQ18rolga16Md4wIRzFNU+JsX7WVIcD
 zPd6PzotAkGD+suqMiYt6ka6cqQT9lB8WN5L88Kdyy8mFsEu7YZBVkWQqB4YCLgu
 7s3vaSuJ9NIGtT3C1Kd2lmEsrDZj84bmEHaP8aOdLAstucNrl8/wSo3NQFeydALQ
 WBpiDhFY2jOYSxcuwI+ZYfeizztr4qGXUaI2VM7/HYSChmWzyvghmP/XmZJDwCKk
 dDgyNSxEjWfM6GD1fmPulvU2MZKabqv6juHpETsPNPdpw7u+Z7om8s2G66erMliU
 WQOfwE4lFcBF0oVoJp2FQQYcme4BERDsqUWJ8C60PW0FELuZlAWRRcUIl49M6gXa
 sSTNfIXubA2LxjHQFS7hy+9+N1Dl1AFcQZP+Md8ai8B4JfDgswf+m1OVuOihDECa
 bMotWVZ+qHeycly9RihDkCas8ICPlCIGZ6PmAPnsMr5Ruzt9oaKuZ5UInB6IRx2k
 H7510dWvJLLZ7w1r78UWdyiT4DH5xRuqQJ8F7erOmtPw5lCmKto=
 =OZk+
 -----END PGP SIGNATURE-----

add license
```

Output from parse commit:

```js
{ parents: [ '32f04c7f572bf75a266268c6f4d8c92731dc3b7f' ],
  hash: '00dd089c310aea2b821d23ea0f1a6a6235ad165c',
  author:
   { name: 'Miguel Mota',
     email: 'hello@miguelmota.com',
     timestamp: 1560727622,
     timezone: '-0700' },
  committer:
   { name: 'Miguel Mota',
     email: 'hello@miguelmota.com',
     timestamp: 1560727622,
     timezone: '-0700' },
  pgp:
   'iQIzBAABCAAdFiEEkA8ilwQdtHsQgZEbZ+wRYViKAPkFAl0G0EYACgkQZ+wRYViK\nAPmWdxAAgWKOQpz1/QbzYxOXQZ5uT8lTVnxw8HN4KZaZ36ehFTxzRVO0IEniJGr4\n5+sVskMDbkP/aKQyS/UUmeXKGeYQT4Kpwvtih5CZHSLNO2LQ8pz5o0wjWK8OHmx7\npGuAd83gMqfnQF7+KDqpxqHR63NDmuRo4QQ18rolga16Md4wIRzFNU+JsX7WVIcD\nzPd6PzotAkGD+suqMiYt6ka6cqQT9lB8WN5L88Kdyy8mFsEu7YZBVkWQqB4YCLgu\n7s3vaSuJ9NIGtT3C1Kd2lmEsrDZj84bmEHaP8aOdLAstucNrl8/wSo3NQFeydALQ\nWBpiDhFY2jOYSxcuwI+ZYfeizztr4qGXUaI2VM7/HYSChmWzyvghmP/XmZJDwCKk\ndDgyNSxEjWfM6GD1fmPulvU2MZKabqv6juHpETsPNPdpw7u+Z7om8s2G66erMliU\nWQOfwE4lFcBF0oVoJp2FQQYcme4BERDsqUWJ8C60PW0FELuZlAWRRcUIl49M6gXa\nsSTNfIXubA2LxjHQFS7hy+9+N1Dl1AFcQZP+Md8ai8B4JfDgswf+m1OVuOihDECa\nbMotWVZ+qHeycly9RihDkCas8ICPlCIGZ6PmAPnsMr5Ruzt9oaKuZ5UInB6IRx2k\nH7510dWvJLLZ7w1r78UWdyiT4DH5xRuqQJ8F7erOmtPw5lCmKto=\n=OZk+',
  title: 'add license',
  description: '' }
```

**Comment by alessioalex** [comment]
Really weird. Will check this out on Wednesday as I'm away atm. Can you perhaps save the input to a file meanwhile and attach it here? Might be a weird char somewhere and I don't want to miss it. 

Thanks for reporting this. 

-- 
 Alexandru Vladutu
 github@social.alessioalex.com


On Sun, Jul 28, 2019, at 13:17, Miguel Mota wrote:
> The tree hash is not being returned. Here's the example input:

> `tree 00dd089c310aea2b821d23ea0f1a6a6235ad165c
parent 32f04c7f572bf75a266268c6f4d8c92731dc3b7f
author Miguel Mota <hello@miguelmota.com> 1560727622 -0700
committer Miguel Mota <hello@miguelmota.com> 1560727622 -0700
gpgsig -----BEGIN PGP SIGNATURE-----

 iQIzBAABCAAdFiEEkA8ilwQdtHsQgZEbZ+wRYViKAPkFAl0G0EYACgkQZ+wRYViK
 APmWdxAAgWKOQpz1/QbzYxOXQZ5uT8lTVnxw8HN4KZaZ36ehFTxzRVO0IEniJGr4
 5+sVskMDbkP/aKQyS/UUmeXKGeYQT4Kpwvtih5CZHSLNO2LQ8pz5o0wjWK8OHmx7
 pGuAd83gMqfnQF7+KDqpxqHR63NDmuRo4QQ18rolga16Md4wIRzFNU+JsX7WVIcD
 zPd6PzotAkGD+suqMiYt6ka6cqQT9lB8WN5L88Kdyy8mFsEu7YZBVkWQqB4YCLgu
 7s3vaSuJ9NIGtT3C1Kd2lmEsrDZj84bmEHaP8aOdLAstucNrl8/wSo3NQFeydALQ
 WBpiDhFY2jOYSxcuwI+ZYfeizztr4qGXUaI2VM7/HYSChmWzyvghmP/XmZJDwCKk
 dDgyNSxEjWfM6GD1fmPulvU2MZKabqv6juHpETsPNPdpw7u+Z7om8s2G66erMliU
 WQOfwE4lFcBF0oVoJp2FQQYcme4BERDsqUWJ8C60PW0FELuZlAWRRcUIl49M6gXa
 sSTNfIXubA2LxjHQFS7hy+9+N1Dl1AFcQZP+Md8ai8B4JfDgswf+m1OVuOihDECa
 bMotWVZ+qHeycly9RihDkCas8ICPlCIGZ6PmAPnsMr5Ruzt9oaKuZ5UInB6IRx2k
 H7510dWvJLLZ7w1r78UWdyiT4DH5xRuqQJ8F7erOmtPw5lCmKto=
 =OZk+
 -----END PGP SIGNATURE-----

add license
`
> Output from parse commit:

> { parents: [ '32f04c7f572bf75a266268c6f4d8c92731dc3b7f' ],
  hash: '00dd089c310aea2b821d23ea0f1a6a6235ad165c',
  author:
   { name: 'Miguel Mota',
     email: 'hello@miguelmota.com',
     timestamp: 1560727622,
     timezone: '-0700' },
  committer:
   { name: 'Miguel Mota',
     email: 'hello@miguelmota.com',
     timestamp: 1560727622,
     timezone: '-0700' },
  pgp:
   'iQIzBAABCAAdFiEEkA8ilwQdtHsQgZEbZ+wRYViKAPkFAl0G0EYACgkQZ+wRYViK\nAPmWdxAAgWKOQpz1/QbzYxOXQZ5uT8lTVnxw8HN4KZaZ36ehFTxzRVO0IEniJGr4\n5+sVskMDbkP/aKQyS/UUmeXKGeYQT4Kpwvtih5CZHSLNO2LQ8pz5o0wjWK8OHmx7\npGuAd83gMqfnQF7+KDqpxqHR63NDmuRo4QQ18rolga16Md4wIRzFNU+JsX7WVIcD\nzPd6PzotAkGD+suqMiYt6ka6cqQT9lB8WN5L88Kdyy8mFsEu7YZBVkWQqB4YCLgu\n7s3vaSuJ9NIGtT3C1Kd2lmEsrDZj84bmEHaP8aOdLAstucNrl8/wSo3NQFeydALQ\nWBpiDhFY2jOYSxcuwI+ZYfeizztr4qGXUaI2VM7/HYSChmWzyvghmP/XmZJDwCKk\ndDgyNSxEjWfM6GD1fmPulvU2MZKabqv6juHpETsPNPdpw7u+Z7om8s2G66erMliU\nWQOfwE4lFcBF0oVoJp2FQQYcme4BERDsqUWJ8C60PW0FELuZlAWRRcUIl49M6gXa\nsSTNfIXubA2LxjHQFS7hy+9+N1Dl1AFcQZP+Md8ai8B4JfDgswf+m1OVuOihDECa\nbMotWVZ+qHeycly9RihDkCas8ICPlCIGZ6PmAPnsMr5Ruzt9oaKuZ5UInB6IRx2k\nH7510dWvJLLZ7w1r78UWdyiT4DH5xRuqQJ8F7erOmtPw5lCmKto=\n=OZk+',
  title: 'add license',
  description: '' }

**Comment by miguelmota** [comment]
Adding the commit hash as the first line fixed it:

```js
const parsed = parseCommit(`${commitHash}\n${commit}`)
```

I used cat-file to get the commit data which doesn't return the commit hash:

```bash
$ git cat-file -p HEAD~4
tree 00dd089c310aea2b821d23ea0f1a6a6235ad165c
parent 32f04c7f572bf75a266268c6f4d8c92731dc3b7f
author Miguel Mota <hello@miguelmota.com> 1560727622 -0700
committer Miguel Mota <hello@miguelmota.com> 1560727622 -0700
gpgsig -----BEGIN PGP SIGNATURE-----

 iQIzBAABCAAdFiEEkA8ilwQdtHsQgZEbZ+wRYViKAPkFAl0G0EYACgkQZ+wRYViK
 APmWdxAAgWKOQpz1/QbzYxOXQZ5uT8lTVnxw8HN4KZaZ36ehFTxzRVO0IEniJGr4
 5+sVskMDbkP/aKQyS/UUmeXKGeYQT4Kpwvtih5CZHSLNO2LQ8pz5o0wjWK8OHmx7
 pGuAd83gMqfnQF7+KDqpxqHR63NDmuRo4QQ18rolga16Md4wIRzFNU+JsX7WVIcD
 zPd6PzotAkGD+suqMiYt6ka6cqQT9lB8WN5L88Kdyy8mFsEu7YZBVkWQqB4YCLgu
 7s3vaSuJ9NIGtT3C1Kd2lmEsrDZj84bmEHaP8aOdLAstucNrl8/wSo3NQFeydALQ
 WBpiDhFY2jOYSxcuwI+ZYfeizztr4qGXUaI2VM7/HYSChmWzyvghmP/XmZJDwCKk
 dDgyNSxEjWfM6GD1fmPulvU2MZKabqv6juHpETsPNPdpw7u+Z7om8s2G66erMliU
 WQOfwE4lFcBF0oVoJp2FQQYcme4BERDsqUWJ8C60PW0FELuZlAWRRcUIl49M6gXa
 sSTNfIXubA2LxjHQFS7hy+9+N1Dl1AFcQZP+Md8ai8B4JfDgswf+m1OVuOihDECa
 bMotWVZ+qHeycly9RihDkCas8ICPlCIGZ6PmAPnsMr5Ruzt9oaKuZ5UInB6IRx2k
 H7510dWvJLLZ7w1r78UWdyiT4DH5xRuqQJ8F7erOmtPw5lCmKto=
 =OZk+
 -----END PGP SIGNATURE-----

add license
```

So this is how I got the commit hash:

```bash
$ git rev-parse HEAD~4
d89f84d948796605a413e196f40bce1d6294175d
```

Prepending it fixed it, but an improvement to this library would be to calculate it if it doesn't exist. Should be easy since the commit id is a sha1 of the commit data.

Feel free to close

**Comment by miguelmota** [comment]
> Prepending it fixed it, but an improvement to this library would be to calculate it if it doesn't exist. Should be easy since the commit id is a sha1 of the commit data.

I take that back, since it's out of scope for this library. I think omitting the `hash` property in this case would be sufficient. The original issue was that it was using the `tree` value as the commit hash when the commit hash didn't exist so I think there's a bug in the regex parsing

**Comment by alessioalex** [comment]
Hi @miguelmota ! Thanks again for reporting this.

The issue is very simple indeed. This library was made to work with the output from `git rev-list` so I didn't take `git cat-file -p` into consideration tbh. 

See the examples below:

```bash
alexandru@LXBU-6SS7HR2:~/www/git-parse-commit/examples git:master 
→ git --git-dir="/home/alexandru/www/git-parse-commit/.git" rev-list --header --max-count=1 HEAD --
66d047bbfec33f18925322fe453d56b3f4097078
tree 2e066289f8aa1351af1a0026d4f9bf23590bd5d9
parent f62e4e6812ef480c2887a080ad33525aa3627668
author Alexandru Vladutu <alexandru.vladutu@gmail.com> 1461243087 +0300
committer Alexandru Vladutu <alexandru.vladutu@gmail.com> 1461243087 +0300

    chore(release): bump version to 1.0.0

alexandru@LXBU-6SS7HR2:~/www/git-parse-commit/examples git:master 
→ git cat-file -p 66d047bbfec33f18925322fe453d56b3f4097078
tree 2e066289f8aa1351af1a0026d4f9bf23590bd5d9
parent f62e4e6812ef480c2887a080ad33525aa3627668
author Alexandru Vladutu <alexandru.vladutu@gmail.com> 1461243087 +0300
committer Alexandru Vladutu <alexandru.vladutu@gmail.com> 1461243087 +0300

chore(release): bump version to 1.0.0
```

However this should be an easy fix (the difference between the 2 is that the hash doesn't exist when using 'cat-file'). I will work on a fix now and publish a new major version. 

:+1:

**Comment by alessioalex** [comment]
Fixed in version `1.1.0`, available on npm.

**Comment by miguelmota** [comment]
@alessioalex  nice, didn't know about `git rev-list --header --max-count=1 HEAD` . Thanks a lot for the updates!

**Comment by alessioalex** [comment]
Np. If you need other `git` related stuff, I basically coded whatever I needed to run my own github locally by shelling out to git (view git commits, trees, files, authors etc): https://github.com/alessioalex?utf8=%E2%9C%93&tab=repositories&q=git&type=source&language=
